#' clique.signal: A package for working with coltron results.
#'
#' The clique.signal package provides functionality for importing results
#' generated by coltron.
#'
#' Coltron was developed by Alex Federation in the Bradner Lab at DFCI,
#' and is used for predicting gene regulatory networks from H3K27Ac
#' ChIP-seq data.
#'
#' @seealso \url{http://www.alexfederation.com/code/},
#' \url{https://pypi.org/project/coltron/}
#'
#' @docType package
#' @name clique.signal
NULL
